# you find the full pre-commit-tools docu under:
# https://pre-commit.com/

repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [ --check, --diff, --config, ./pyproject.toml ]
        language_version: python3.10
        stages: [ push ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        args: [ --profile, black, --check, --diff ]
        language_version: python3.10
        stages: [ push ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [ pep8-naming, flake8-bugbear ]
        args: [ --config=./setup.cfg, -v, --count ]
        language_version: python3.10
        stages: [ push ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
        language_version: python3.10
        stages: [ push ]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "2.2"]
        language_version: python3.10
        stages: [ push ]
